jobs:
  include:
    - stage: "Api tests and linters"
      language: php
      php:
        - '7.4'
      script:
        - cd Api && make dependencies && make test

    - stage: "Frontend tests and linters"
      language: node_js
      node_js: 13
      script:
        - cd WebInterface && make dependencies && make lint